version: '3.9'
services:
  node:
    image: ma_super_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=your-username
      - DATABASE_PASSWORD=your-password
      - DATABASE_NAME=your-db-name
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=your-db-name
      - MYSQL_USER=your-username
      - MYSQL_PASSWORD=your-password
      - MYSQL_ROOT_PASSWORD=your-root-password
